# ==============================================================
# WAX CONFIGURATION
# ==============================================================
# Jekyll configuration files are written in YAML format.
# Colons, tabs/spacing, and quotes are meaningful in YAML.
# It is recommended you look at the following guide to avoid
# syntax errors in this file:
# ~> https://learnxinyminutes.com/docs/yaml/
#
#
# Questions ?
# ~> https://minicomp.github.io/wiki/#/
# ~> https://gitter.im/minicomp/wax/
#
# ---------------------------------------------------------------
# MAIN SETTINGS
# ---------------------------------------------------------------
# Feel free to change these! For more info, refer to:
# ~> https://jekyllrb.com/docs/configuration/options/

title:            'SpokenWeb UAlberta'
description:      'Audiotextual Collection'
url:              'https://cmiya.github.io'
baseurl:          '/spokenweb-ualberta'
copyright:        'copyright SpokenWeb, 2023'
logo:             '/assets/logo-white.png'

# ---------------------------------------------------------------
# BUILD SETTINGS
# ---------------------------------------------------------------
# Best not to mess with these unless you know what you're doing!

permalink: 'pretty'
sass:
  style: compressed
exclude:
  - Gemfile*
  - Rakefile
  - vendor
  - spec
  - README.md
incremental: true
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'
kramdown:
 auto_ids:       true
 footnote_nr:    1
 entity_output:  as_char
 footnote_backlink: "&#x21a9;&#xfe0e;"
 toc_levels:     1..6
 smart_quotes:   lsquo,rsquo,ldquo,rdquo
 enable_coderay: false

# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  pages:
    index: '/search/pages.json' # file the index will get written to
    fields: # the metadata fields to index
      - title
      - author
      - publish_date
      - Rights Statement
      - Duration
      - Agent
      - Date
      - Language
      - Format
      - Subject
      - Type
      - Note
      - Event Location


# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: 'About'
    sub:
      - label: 'Our Team'
        link: '/team/'
      - label: 'Background'
        link: '/about/'
      - label: 'Collection'
        link: '/collection/'
      - label: 'Search'
        link: '/search'
  - label: 'Events'
    sub:
      - label: "All Events"
        link: '/events/'
      - label: "Featured Events"
        link: '/featured_events'
  - label: 'Featured Exhibits'
    sub:
      - label: 'Voiceprint'
        link: '/exhibits/voiceprint/'
      - label: 'Jars Balan'
        link: '/exhibits/jarsBalan/'
      - label: 'Celebrations'
        link: '/exhibits/celebrations/'

# --------------------------------------------------------------
# SITE FOOTER SETTINGS
# --------------------------------------------------------------
#

footer:
  links:
    - label: 'GitHub'
      link: 'https://github.com/cmiya/spokenweb-ualberta'
    - label: 'Our Team'
      link: '/team'
    - label: 'Contact'
      link: '/contact'
  logos:
    - img: '/img/logo-white.png'

# FIN
